### ISSUE TITLE
Projekt Deployfähig machen

### ISSUE THREAD

**Issue by N-I-K-E-Lx64** [Projekt-Bachelor/Poker#12]

**Comment by N-I-K-E-Lx64** [comment]
Sobald der Master Branch mit dem Server Branch gemergt wird, sollte es funktionieren. Dort wird die momentane CApplication Main Methode durch "SpringApplication.run(...)" ersetzt.

**Comment by flashpixx** [comment]
Ich würde für das Testing einen Unit-Test empfehlen und nicht die main-Methode, somit wäre der Master-Branch immer funktionsfähig

**Comment by N-I-K-E-Lx64** [comment]
Projekt wird automatisch auf Heroku deployt und funktioniert dort einwandfrei.
