### ISSUE TITLE
Erstelle eine Art GameState, der alle Ereignisse des Spiels protokolliert

### ISSUE THREAD

**Issue by N-I-K-E-Lx64** [Projekt-Bachelor/Poker#14]
Dieses Log wird im Prototypen (ohne UI) dazu genutzt, das Spielgeschehen abzubilden und um später diese Funktion auf einen anderen Thread auszulagern, damit nicht die Spiellogik jedes Mal pausiert wird.

Hierbei werden alle Aktionen protokolliert und wenn die _notifyAllClients_ - Funktion aufgerufen wird. Wird dieses Log komplett verschickt, sodass alle Clients auf dem selben Stand sind.

**Comment by N-I-K-E-Lx64** [comment]
Okay du hast recht, der Begriff "Log" hat dafür nicht gepasst.

Was Hendrik und ich uns überlegt hatten, dass wir für die ersten 2 Meilensteine anpeilen, dass wir das Spielgeschehen als einen fortlaufenden Textfluss darstellen. Erst wenn die Netzwerkarchitektur und das Backend stehen, wollen wir uns mit dem UI (Phaser) beschäftigen.

Außerdem haben wir wenigstens dann etwas zu zeigen und können auch gleichzeitig testen ob unsere Spiele-Logik funktioniert.

**Comment by flashpixx** [comment]
Mein Vorschlag direkt Json nehmen, dann habt ihr nachher weniger Arbeit in der UI, sprich baut die Controller und schickt dann einfach die Daten hin und her. Ihr müsst entscheiden, ob ihr einen REST-Controller baut oder einen Websocket verwendet (kann aber auch ggf später tauschen).

Als Tools für die Entwicklung bieten sich entsprechende Browsererweiterungen an:

* https://www.getpostman.com/
* https://install.advancedrestclient.com/
* https://chrome.google.com/webstore/detail/smart-websocket-client/omalebghpgejjiaoknljcfmglgbpocdp

**Comment by N-I-K-E-Lx64** [comment]
Dieser Gamestate ermöglicht eine Art Text-Adventure wo alle Ereignisse / Aktionen der Spieler protokolliert und vom UI dargestellt werden können.

*Benötigte Funktionen*
- Zurücksetzen nach jeder Runde
