### ISSUE TITLE
Merge von Spielelogik in den Masterbranch

### ISSUE THREAD

**Issue by HendrikCz** [Projekt-Bachelor/Poker#21]
Merge und erstellen eines übergreifenden Hubs, der mit allen Teilen des Codes interagieren kann.

**Comment by N-I-K-E-Lx64** [comment]
Merge was successful!

**Comment by flashpixx** [comment]
Der [CircleCI Build](https://circleci.com/gh/Projekt-Bachelor/Poker/43) ist gebrochen

**Comment by N-I-K-E-Lx64** [comment]
Das BuildLog besagt, dass eine nicht importierte dependency benutzt wurde. Diese wurde vermutlich nur aus Versehen importiert, da sie im Code nicht benutzt wurde. Sollte im nächsten Commit gefixt sein.

**Comment by flashpixx** [comment]
Auch mal [Warnungen](https://circleci.com/gh/Projekt-Bachelor/Poker/45) anschauen

**Comment by N-I-K-E-Lx64** [comment]
Jetzt funktioniert es momentan wieder :)
