### ISSUE TITLE
Kommunikations Objekte definieren

### ISSUE THREAD

**Issue by N-I-K-E-Lx64** [Projekt-Bachelor/Poker#27]
Objekte / Klassen für Aktionen und Antworten erstellen.

**Aktionen**:
- **Raise**: player-Object, amount
- **Check**: player-Object
- **Fold**: player-Object
- **Call**: player-Object
- **All-In**: player-Object

Check, Fold, Call, "All-In" funktionieren Server Seitig. Das jeweilige Player-Object wird anhand der Session-List abstrahiert.

**Comment by N-I-K-E-Lx64** [comment]
@HendrikCz am besten kuckst du nochmal nach, welche Infos bzw. Parameter du für die einzelnen Funktionen der Spiele-Logik gegebenenfalls noch brauchst, sodass ich diese Klassen konkret implementieren kann.

**Comment by HendrikCz** [comment]
SpielAktionen sind alle erstellt

**Comment by N-I-K-E-Lx64** [comment]
*siehe Issue* **Server-Client-Kommunikation**
