### ISSUE TITLE
REST Controller / WebSocket

### ISSUE THREAD

**Issue by flashpixx** [Projekt-Bachelor/Poker#3]
Einen einfachen Controller erstellen, der Daten austauschen kann [siehe Dokumentation](https://spring.io/guides/gs/rest-service/). Client für das Testing

* http://restclient.net/
* https://chrome.google.com/webstore/detail/advanced-rest-client/hgmloofddffdnphfgcellkdfbfbjeloo?hl=de
* oder einfach im Browser die URL aufrufen

**Comment by N-I-K-E-Lx64** [comment]
Kommunikation soll über einen WebSocket statt über REST erfolgen.

**Comment by N-I-K-E-Lx64** [comment]
Websocket Architektur ist implementiert.
